add stats
SemekhinV/java-explore-with-me pull request #3
Opened 2023-10-07 15:41 UTC by SemekhinV

2023-10-16 21:03 UTC, NikolaiDem requested changes

2023-10-16 21:03 UTC, NikolaiDem commented on docker-compose.yml
> +      - POSTGRES_USER=stats
Эти переменные не используются.
Можно
 задать spring.datasource.username и spring.datasource.password в application.properties через эти переменные среды

или

здесь задать переменные среды SPRING_DATASOURCE_USERNAME и SPRING_DATASOURCE_PASSWORD вместо POSTGRES_USER и POSTGRES_PASSWORD

2023-10-17 11:27 UTC, SemekhinV commented on ewm/pom.xml
> +            <version>0.0.1-SNAPSHOT</version>
Здравствуйте, сделал

2023-10-17 11:27 UTC, SemekhinV commented on stats/stats-dto/pom.xml
> +            <version>2.14.2</version>
Сделал

2023-10-17 11:27 UTC, SemekhinV commented on stats/stats-dto/pom.xml
> +            <version>1.18.26</version>
Сделал

2023-10-17 11:27 UTC, SemekhinV commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/HitDto.java
> +@Data
Убрал аннотации и сделал, как вы сказали

2023-10-17 11:27 UTC, SemekhinV commented on stats/stats-dto/src/main/java/ru/practicum/stats/dto/HitDto.java
> +    @NotNull
Убрал

2023-10-17 23:51 UTC, NikolaiDem approved these changes

2023-10-18 07:51 UTC, merged