add main_svc
SemekhinV/java-explore-with-me pull request #4
Opened 2023-10-24 12:36 UTC by SemekhinV

2024-01-27 11:45 UTC, NikolaiDem requested changes

2024-01-27 11:45 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/service/admin/EventAdminServiceImpl.java
> +        if (rangeEnd != null && rangeStart != null && rangeStart.isAfter(rangeEnd)) {
Валидацию лучше делать в контроллере

2024-01-27 11:45 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/service/admin/EventAdminServiceImpl.java
> +        result.forEach(event -> event.setViews(getViews(event)));
getViews не нужно вызывать в каждой итерации, нужно получить все просмотры за одно обращение к сервису статистики.
Аналогично для mapToShortDtoAndAddView

2024-01-27 11:45 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/service/admin/EventAdminServiceImpl.java
> +        if (dto.getEventDate() != null && dto.getEventDate().isBefore(LocalDateTime.now().plusHours(1))) {
Валидацию лучше делать в контроллере

2024-01-27 11:45 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/service/user/EventUserServiceImpl.java
> +        events.forEach(event -> sendStatsForTheEvent(event.getId(), request.getRemoteAddr(), now));
Эта отправка статистики лишняя, выше уже есть запрос к сервису статистики

2024-01-27 13:26 UTC, SemekhinV commented on ewm/src/main/java/ru/practicum/ewm/error/controller/ErrorHandler.java
> +
Сделал логирование ошибок в ErrorHandle

2024-01-27 20:14 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/entity/Event.java
> +    private Long confirmedRequests;
Даже если оставить это поле здесь, то у нас появляется 2 источника истины (это поле и сами исходные запросы), между которыми нужно постоянно поддерживать синхронизацию, а это дополнительные расходы.
Даже если мы хотим избавиться от просмотра всех реквестов при получении списка событий, то запоминать количество запросов лучше на уровне нового entity, которое предусмотрено именно для просмотров (так называемый паттерн CQRS).
Например, у нас очень много просмотров событий, в которые нужно добавить инфо о самом событии, количестве запросов, юзерах и много еще чего, тогда можем создать новую таблицу, которая будет являться таким большим агрегатом событий, реквестов, юзеров и т.д., и которая будет обновляться каждый раз, когда меняется событие, юзер, реквест и т.д. То есть пишем в одни таблицы, а читаем из других (из агрегированных). В этом случае можем повысить производительность.
Поэтому, если в нашем сервисе будет просмотров намного больше чем обновлений, то делать предварительные расчеты (confirmedRequests) логично при самом обновлении реквеста, да, но все же лучше не в этом энтити. А если такого требования у нас нет, то от поля confirmedRequests можно вовсе избавиться

2024-01-28 11:50 UTC, SemekhinV commented on ewm/src/main/java/ru/practicum/ewm/event/entity/Event.java
> +    private Long confirmedRequests;
Большое спасибо, логично и понятно. Я прочитал несколько статей про архитектуру CQRS и понял, о чем речь. Но у меня к вам еще один небольшой вопрос, правда уже не по теме. Порекомендуйте, пожалуйста, если читали, книги про виды и принципы создания архитектуры приложений. У меня по работе свой проект по парсингу конфигураций, который нужно переписать, а мне не хватает знаний. Буду очень признателен.

2024-01-29 21:37 UTC, NikolaiDem approved these changes

2024-01-29 21:37 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/event/service/admin/EventAdminServiceImpl.java
> +    private Map<Long, Long> getViewsMap(List<ViewStatsDto> stats) {
В функциональном стиле код выглядит проще:
    private Map<Long, Long> getViewsMap(List<ViewStatsDto> stats) {
        return stats.stream()
                .collect(Collectors.toMap(viewStatsDto -> getEventIdFromStats(viewStatsDto.getUri()), ViewStatsDto::getHits));
    }

2024-01-29 21:37 UTC, NikolaiDem commented on ewm/src/main/java/ru/practicum/ewm/request/service/RequestServiceImpl.java
> +        var requestCount = requests.stream()
Чтобы не перебирать коллекцию requests для каждого события, лучше представить requests в виде мапы, где ключ - id события, а значение - список его запросов

2024-01-30 11:55 UTC, merged